### PR TITLE
Use conventional package folder structure

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Hi @xl0418,

Instead of just emailing, I've also just done it: made this repo follow a conventional folder structure.

Feel free to reject, but accepting would be a natural thing to do :+1:

### CODE REVIEW

**Comment by xl0418** [comment]
Folder structure corrected

**Comment by richelbilderbeek** [comment]
@xl0418: you need to log in. There will be a big green button you need to click :+1: 

You can do it :rainbow: !

**Comment by richelbilderbeek** [comment]
Great! Don't forget to update (`git pull`) your local version :rainbow:

**Comment by richelbilderbeek** [comment]
Behold, [the first repo depending on it](https://github.com/richelbilderbeek/razzo/issues/144) :+1:

**Pull request merged**
